title: Product Brain
description: A knowledge base for all things Digital Product Management and related
theme: just-the-docs

url: https://pmpreis.github.io/productbrain

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template


ga_tracking: G-45X5PQ7FE5
ga_tracking_anonymize_ip: true 

plugins:
  - jekyll-default-layout
  - jekyll-seo-tag